"""initial open agent kit schema

Revision ID: fc80e29dcd57
Revises: 
Create Date: 2026-07-11 23:08:11.856432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc80e29dcd57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_defs_name', 'agent_definitions', ['name'], unique=False)
    op.create_index('idx_agent_defs_type', 'agent_definitions', ['type'], unique=False)
    op.create_table('config_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('config_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=64), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_snapshots_created_at', 'config_snapshots', ['created_at'], unique=False)
    op.create_index('idx_config_snapshots_type_id', 'config_snapshots', ['config_type', 'config_id'], unique=False)
    op.create_index('idx_config_snapshots_version', 'config_snapshots', ['config_type', 'config_id', 'version'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_active', 'sessions', ['active'], unique=False)
    op.create_index('idx_sessions_created_at', 'sessions', ['created_at'], unique=False)
    op.create_index('idx_sessions_updated_at', 'sessions', ['updated_at'], unique=False)
    op.create_table('tool_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_defs_name', 'tool_definitions', ['name'], unique=False)
    op.create_index('idx_tool_defs_type', 'tool_definitions', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_active', 'users', ['active'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_defs_name', 'workflow_definitions', ['name'], unique=False)
    op.create_index('idx_workflow_defs_updated_at', 'workflow_definitions', ['updated_at'], unique=False)
    op.create_table('workflow_test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_message', sa.Text(), nullable=False),
    sa.Column('expected_agent', sa.String(length=255), nullable=True),
    sa.Column('expected_tools', sa.JSON(), nullable=True),
    sa.Column('expected_output_contains', sa.JSON(), nullable=True),
    sa.Column('expected_output_pattern', sa.String(length=500), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_test_cases_workflow_id'), 'workflow_test_cases', ['workflow_id'], unique=False)
    op.create_table('workflow_test_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('error_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('run_by', sa.String(length=255), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_test_runs_workflow_id'), 'workflow_test_runs', ['workflow_id'], unique=False)
    op.create_table('agent_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.Enum('ORCHESTRATOR', 'REASONING', 'KNOWLEDGE', 'RESPONSE', name='agenttype'), nullable=False),
    sa.Column('note_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('note_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_notes_agent_type', 'agent_notes', ['agent_type'], unique=False)
    op.create_index('idx_agent_notes_note_type', 'agent_notes', ['note_type'], unique=False)
    op.create_index('idx_agent_notes_session_id', 'agent_notes', ['session_id'], unique=False)
    op.create_index('idx_agent_notes_timestamp', 'agent_notes', ['timestamp'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_active', 'api_keys', ['active'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'AGENT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False)
    op.create_index('idx_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_index('idx_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_table('workflow_test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('actual_response', sa.Text(), nullable=True),
    sa.Column('actual_agent', sa.String(length=255), nullable=True),
    sa.Column('actual_tools', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_trace', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('run_by', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_test_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['workflow_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_test_results_workflow_id'), 'workflow_test_results', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_test_results_workflow_id'), table_name='workflow_test_results')
    op.drop_table('workflow_test_results')
    op.drop_index('idx_messages_timestamp', table_name='messages')
    op.drop_index('idx_messages_session_id', table_name='messages')
    op.drop_index('idx_messages_role', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_agent_notes_timestamp', table_name='agent_notes')
    op.drop_index('idx_agent_notes_session_id', table_name='agent_notes')
    op.drop_index('idx_agent_notes_note_type', table_name='agent_notes')
    op.drop_index('idx_agent_notes_agent_type', table_name='agent_notes')
    op.drop_table('agent_notes')
    op.drop_index(op.f('ix_workflow_test_runs_workflow_id'), table_name='workflow_test_runs')
    op.drop_table('workflow_test_runs')
    op.drop_index(op.f('ix_workflow_test_cases_workflow_id'), table_name='workflow_test_cases')
    op.drop_table('workflow_test_cases')
    op.drop_index('idx_workflow_defs_updated_at', table_name='workflow_definitions')
    op.drop_index('idx_workflow_defs_name', table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tool_defs_type', table_name='tool_definitions')
    op.drop_index('idx_tool_defs_name', table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index('idx_sessions_updated_at', table_name='sessions')
    op.drop_index('idx_sessions_created_at', table_name='sessions')
    op.drop_index('idx_sessions_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_config_snapshots_version', table_name='config_snapshots')
    op.drop_index('idx_config_snapshots_type_id', table_name='config_snapshots')
    op.drop_index('idx_config_snapshots_created_at', table_name='config_snapshots')
    op.drop_table('config_snapshots')
    op.drop_index('idx_agent_defs_type', table_name='agent_definitions')
    op.drop_index('idx_agent_defs_name', table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
